### ISSUE TITLE
Instrumentation Amplifier

### ISSUE THREAD

**Issue by Keith-Khadar** [Keith-Khadar/Gh05t#5]
Look into the circuit needed to amplify the signal from the electrodes into a useable form.

**Comment by piprtay** [comment]
There are some projects that use this as their signal amplifier : https://docs.rs-online.com/6d2f/A700000006877304.pdf
The lowest price I found was $55. We can look at this for reference since this also combines a instrumentation amplifer, 4 channel op amp ic, reference voltage ic, and some other components.

**Comment by Keith-Khadar** [comment]
Here is an article on how to make a portable eeg, they also describe the circuit they used for their instrumentation amplifier 
Luan B, Sun M, Jia W. Portable Amplifier Design for a Novel EEG Monitor in Point-of-Care Applications. Proc IEEE Annu Northeast Bioeng Conf. 2012;2012:388-389. doi: 10.1109/nebc.2012.6207127. PMID: 25339843; PMCID: PMC4203429.

**Comment by Keith-Khadar** [comment]
https://www.bitbrain.com/blog/eeg-amplifier

This talks about all the specs we need for the amplifier
